spring.application.name=Boycott
### DATABASE ###
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Boycott?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8089
server.servlet.context-path=/Boycott